def _read_choice(valid_options):
    while True:
        choice = input("\nEscolha uma opcao: ").strip()
        if choice in valid_options:
            return choice
        print("Opcao invalida. Tente novamente.")


def show_main_menu():
    print("\nMENU PRINCIPAL:")
    print("1) Scanner Nmap")
    print("2) Recuperar chave privada (GPG + paperkey)")
    print("3) Criptografar arquivo com GPG")
    print("4) Criptografar texto com GPG (armor)")
    print("0) Sair")
    return _read_choice({"0", "1", "2", "3", "4"})


def show_nmap_menu():
    print("\nNMAP - ESCOLHA UMA OPCAO:")
    print("1) Escanear a rede sem fazer conexoes (descobre hosts ativos)")
    print("2) Verificar quais hosts estao ativos na rede")
    print("3) Identificar os servicos (versoes) em execucao no host")
    print("4) Escanear com SYN (modo silencioso)")
    print("5) Escanear UDP (servicos como DNS, DHCP, etc.)")
    print("6) Escanear com TCP (modo completo)")
    print("7) Listar todos os IPs da rede sem escaneamento")
    print("8) Escanear apenas as portas 22, 80 e 443")
    print("9) Escanear todas as portas (1-65535)")
    print("10) Escanear com opcoes avancadas (servicos, versao do sistema, etc.)")
    print("11) Identificar o sistema operacional do host")
    print("12) Escanear em modo detalhado (verbose)")
    print("13) Escanear IPs de um arquivo (ips.txt)")
    print("14) Escanear IPs de um arquivo e portas especificas")
    print("15) Identificar servicos em IPs de um arquivo")
    print("16) Escanear IPs de um arquivo com SYN e portas especificas")
    print("17) Escanear DNS (porta 53) de IPs de um arquivo")
    print("18) Escanear com TCP e portas especificas de IPs de um arquivo")
    print("19) Listar IPs de um arquivo sem escaneamento")
    print("20) Verificar quais hosts estao ativos no arquivo ips.txt")
    print("21) Escanear todas as portas TCP de IPs de um arquivo")
    print("22) Escanear todas as portas UDP de IPs de um arquivo")
    print("23) Identificar servicos em portas especificas de IPs de um arquivo")
    print("24) Escanear com opcoes avancadas de IPs de um arquivo")
    print("25) Identificar o sistema operacional de IPs de um arquivo")
    print("26) Escanear portas especificas de IPs de um arquivo com verbose")
    print("27) Escanear DNS de IPs de um arquivo com verbose")
    print("28) Escanear portas TCP de IPs de um arquivo com verbose")
    print("29) Escanear todas as portas TCP de IPs de um arquivo com verbose")
    print("30) Escanear todas as portas UDP de IPs de um arquivo com verbose")
    print("31) Identificar servicos em todas as portas de IPs de um arquivo com verbose")
    print("32) Escanear com opcoes avancadas de IPs de um arquivo com verbose")
    print("33) Identificar o sistema operacional de IPs de um arquivo com verbose")
    print("34) Escanear portas especificas com identificacao de servicos")
    print("35) Escanear DNS com identificacao de servicos")
    print("36) Escanear portas TCP com identificacao de servicos")
    print("37) Escanear todas as portas TCP com identificacao de servicos")
    print("38) Escanear todas as portas UDP com identificacao de servicos")
    print("39) Escanear portas especificas com identificacao de sistema operacional")
    print("40) Escanear DNS com identificacao de sistema operacional")
    print("41) Escanear portas TCP com identificacao de sistema operacional")
    print("42) Escanear todas as portas TCP com identificacao de sistema operacional")
    print("43) Escanear todas as portas UDP com identificacao de sistema operacional")
    print("44) Escanear portas especificas com identificacao de servicos e sistema operacional")
    print("45) Escanear DNS com identificacao de servicos e sistema operacional")
    print("46) Escanear portas TCP com identificacao de servicos e sistema operacional")
    print("47) Escanear todas as portas TCP com identificacao de servicos e sistema operacional")
    print("48) Escanear todas as portas UDP com identificacao de servicos e sistema operacional")
    return _read_choice({str(i) for i in range(1, 49)})


def show_kleopatra_menu():
    print("\nKLEOPATRA:")
    print("1) Criptografar texto")
    print("2) Descriptografar texto")
    print("3) Criptografar arquivo")
    print("4) Descriptografar arquivo")
    print("5) Reconstruir chave privada")
    print("0) Voltar")
    return _read_choice({"0", "1", "2", "3", "4", "5"})


def show_zip_menu():
    print("\nZIP/COMPACTACAO:")
    print("1) Extrai .gz")
    print("2) Compacta em .gz")
    print("3) Extrai .zip")
    print("4) Cria .zip")
    print("5) Zipa diretorio recursivamente")
    print("6) Zipa com senha")
    print("7) Extrai para diretorio especifico")
    print("8) Testa integridade do .zip")
    print("9) Cria .tar.gz")
    print("10) Extrai .tar.gz")
    print("11) Cria .tar.bz2")
    print("12) Extrai .tar.bz2")
    print("13) Cria .tar.xz")
    print("14) Extrai .tar.xz")
    print("15) Cria .7z")
    print("16) Extrai .7z")
    print("17) Cria .rar")
    print("18) Extrai .rar")
    print("19) Cria .a (biblioteca)")
    print("20) Extrai .a")
    print("21) Compacta em .bz2")
    print("22) Extrai .bz2")
    print("23) Compacta em .xz")
    print("24) Extrai .xz")
    print("25) Cria .cpio")
    print("26) Extrai .cpio")
    print("27) Le conteudo sem extrair (.gz)")
    print("28) Le conteudo sem extrair (.bz2)")
    print("29) Le conteudo sem extrair (.xz)")
    print("30) Lista conteudo sem extrair (.7z)")
    print("0) Voltar")
    return _read_choice({"0"} | {str(i) for i in range(1, 31)})


def show_ssh_menu():
    print("\nSSH:")
    print("1) Gerar par de chaves SSH para GitHub")
    print("2) Gerar par de chaves e conectar maquina remota por chave SSH")
    print("0) Voltar")
    return _read_choice({"0", "1", "2"})


def show_docker_menu():
    print("\nDOCKER:")
    print("1) Criar container Debian")
    print("2) Criar container Ubuntu")
    print("3) Criar container Debian com senha (SSH)")
    print("4) Criar container Ubuntu com senha (SSH)")
    print("5) Entrar em um container")
    print("6) Apagar container")
    print("0) Voltar")
    return _read_choice({"0", "1", "2", "3", "4", "5", "6"})
